### PR TITLE
Added New Resource NetIPInterface - Fixes #355 

### LINKED ISSUE #355: Set-NetIPInterface -Forwarding Enabled
This command is often used in lab setups to enable forwarding between NICs without setting up routing infrastructure.

But I don't see anything in this resource module which allows that. Have I missed it?

### PR DESCRIPTION
**Pull request by PlagueHO**
#### Pull Request (PR) description

This PR adds the NetIPInterface resource for configuring the Network IP interface settings on an adapter.

#### This Pull Request (PR) fixes the following issues

- Fixes #355 

#### Task list
- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in README.md in resource folder.
- [x] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

@johlju - this is a bit of a large one (being a new resource). Would you mind reviewing when you have a chance? No rush at all!

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/networkingdsc/361)

### CODE REVIEW

**Comment by johlju** [comment]
Been busy at work, and also upgrading my home lab (it was time, hardware was getting old). Will look at this as soon as I can.

**Comment by PlagueHO** [comment]
No worries at all @johlju - I totally understand - no rush. Building it just in time for WS2019. I guess I'll need to start testing all these modules on WS2019 soon. Hope AppVeyor provides a 2019 agent quickly.

**Comment by johlju** [comment]
Or use a container, if that is possible, the Windows Server 2019 container is probably available sooner. :)

**Comment by PlagueHO** [comment]
Worth a try :grin: Although given that the image was pulled recently I'm not sure either are coming any time soon :grin:

**Comment by johlju** [comment]
There are conflicting files, so you need to rebase too :sli

**Comment by PlagueHO** [comment]
Thank you @johlju

**Pull request merged**
