### PR TITLE
Test-DscParameterState Enhancements

### LINKED ISSUE #401: Test-DscParameterState: Some general fixes and improvments
#### Details of the scenario you tried and the problem that is occurring
Test-DscParameterState does not always return the expected value.  It is also lacking some features that are described below.

I would like to work on this as I need the functionality for some new resources.

#### Verbose logs showing the problem
1. Even if types don't match, it returns $true
``` PowerShell
Import-Module -Name C:\Git\NetworkingDsc\Modules\NetworkingDsc.Common\NetworkingDsc.Common.psm1 -Force

$current = @{
    List = [string[]]('a', 'b', 'c')
    Value = 'test'
}

$desired = @{
    List = 'a', 'b', 'c'
    Value = 'test'
}

Test-DscParameterState -CurrentValues $current -DesiredValues $desired -Verbose
```

```
VERBOSE: NOTMATCH: Type mismatch for property 'List' Current state type is 'String[]' and desired type is 'Object[]'.
VERBOSE: MATCH: Value (type 'String') for property 'Value' does match. Current state is 'test' and desired state is 'test'.
VERBOSE: Test-DscParameter result is 'True'.
True
```

---

2. Ordering of values sometimes doesn't matter and / or cannot be controlled. It would be great if the function can deal with the following sample and return $true even if the order is different.

``` PowerShell
Import-Module -Name C:\Git\NetworkingDsc\Modules\NetworkingDsc.Common\NetworkingDsc.Common.psm1 -Force

$current = @{
    List = 'c', 'b', 'a'
    Value = 'test'
}

$desired = @{
    List = 'a', 'b', 'c'
    Value = 'test'
}

Test-DscParameterState -CurrentValues $current -DesiredValues $desired -Verbose
```

```
VERBOSE: Comparing values in property 'List'.
VERBOSE: NOTMATCH: Value [0] (type 'String') for property 'List' does match. Current state is 'c' and desired state is 'a'.
VERBOSE: MATCH: Value [1] (type 'String') for property 'List' does match. Current state is 'b' and desired state is 'b'.
VERBOSE: NOTMATCH: Value [2] (type 'String') for property 'List' does match. Current state is 'a' and desired state is 'c'.
VERBOSE: MATCH: Value (type 'String') for property 'Value' does match. Current state is 'test' and desired state is 'test'.
VERBOSE: Test-DscParameter result is 'False'.
False
```

---

3. If a setting is not in the desired but in the current state, Test-DscParameterState returns $true and does not recognize the difference. An optional reverse check could handle this.

``` PowerShell
Import-Module -Name C:\Git\NetworkingDsc\Modules\NetworkingDsc.Common\NetworkingDsc.Common.psm1 -Force

$current = @{
    List = 'a', 'b', 'c'
    Value = 'test'
}

$desired = @{
    List = 'a', 'b', 'c'
}

Test-DscParameterState -CurrentValues $current -DesiredValues $desired -Verbose
```
```
VERBOSE: Comparing values in property 'List'.
VERBOSE: MATCH: Value [0] (type 'String') for property 'List' does match. Current state is 'a' and desired state is 'a'.
VERBOSE: MATCH: Value [1] (type 'String') for property 'List' does match. Current state is 'b' and desired state is 'b'.
VERBOSE: MATCH: Value [2] (type 'String') for property 'List' does match. Current state is 'c' and desired state is 'c'.
VERBOSE: Test-DscParameter result is 'True'.
True
```

#### Suggested solution to the issue
Extending the feature set of the function to:
1. Support a reverse check (Switch parameter 'ReverseCheck')
1. Support internal ordering (Switch parameter 'SortArrayValues')
1. Fix issue 1 in the list above

Also I would live to have support for CimInstance objects.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
none

#### The operating system the target node is running
This is OS independent.

#### Version and build of PowerShell the target node is running
OSVersion                      5.1.14393.0

#### Version of the DSC module that was used ('dev' if using current dev branch)
NA

### PR DESCRIPTION
**Pull request by raandree**
#### Pull Request (PR) description
Enhancements for Test-DscParameterState:
- It can now deal with hashtables and CimInstance arrays
- It provides an optional reverse checks. This is for actively detecting properties in the current state that are missing in the desired state. 
- It can optionally internally sort arrays if the order is not important
- Fixes a bug in Test-DscParameterState where even if types did not match the function returned $true

This PR actually targets only the function Test-DscParameterState and the new functions ConvertTo-CimInstance and ConvertTo-Hashtable now required by Test-DscParameterState. All other code in the common module was only touched by the VSCode code style formatter.

#### This Pull Request (PR) fixes the following issues
Fixes #401 

#### Task list
- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md in resource folder.
- [ ] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/networkingdsc/402)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Hi @raandree - just some line length issues with the markdown:
https://ci.appveyor.com/project/PowerShell/networkingdsc/builds/24932653?fullLog=true#L1632

I'll review once they are fixed.

**Comment by raandree** [comment]
Hi @PlagueHO, I am not getting this. The lines that I have added to the changelog.md are shorter than many others in the file. This error seems to me more like a warning, isn't it?

The errors that I can see are these ones:
https://ci.appveyor.com/project/PowerShell/networkingdsc/builds/24932653?fullLog=true#L2414
```
        [-] Should not be missing the localized string key InvalidCurrentValuesError from the localization resource file 129ms
2415
          Expected 'InvalidCurrentValuesError' to be found in collection @('InterfaceAliasNotFoundError', 'DNSServerStaticAddressNotSetMessage', 'NoMatchValueDifferentCountMessage', 'NoMatchElementTypeMismatchMessage', 'NoMatchPsCredentialUsernameMessage', 'NoMatchTypeMismatchMessage', 'MatchPsCredentialUsernameMessage', 'NoMatchValueMessage', 'GettingDNSServerStaticAddressMessage', 'MultipleMatchingNetAdapterFound'), because the key is used in the resource/module script file so it should also exist in the localized string resource files, but it was not found.
2416
          1412:                         $englishLocalizedStrings.Keys | Should -Contain $LocalizedKey -Because 'the key is used in the resource/module script file so it should also exist in the localized string resource files'
2417
          at <ScriptBlock>, C:\projects\networkingdsc\DscResource.Tests\Meta.Tests.ps1: line 1412
2418
        [+] Should not be missing the localized string key InvalidDesiredValuesError from the localization resource file 40ms
2419
        [+] Should not be missing the localized string key InvalidNetAdapterNumberError from the localization resource file 36ms
2420
        [+] Should not be missing the localized string key InvalidValuesToCheckError from the localization resource file 32ms
```

https://ci.appveyor.com/project/PowerShell/networkingdsc/builds/24932653?fullLog=true#L5583
```
   Context When adapter exists and is enabled, desired state is enabled, no action required
5583
Set-TargetResource : Set-TargetResource: Failed to set network adapter 'Ethernet' to state 'Enabled'. Error: 'No MSFT_NetAdapter objects found with property 'Name' equal to 'Ethernet'.  Verify the value of the property and 
5584
retry.'.
5585
At C:\projects\networkingdsc\Tests\Unit\MSFT_NetAdapterState.Tests.ps1:129 char:23
5586
+ ...                { Set-TargetResource @setTargetResourceEnabled } | Sho ...
5587
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
5588
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
5589
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Set-TargetResource
5590
 
5591
      [+] Should not throw an exception 174ms
5592
      [+] Should not call Disable-NetAdapter 31ms

**Comment by PlagueHO** [comment]
Hi @raandree - ah right, I missed the other two errors. 

The two long lines in the Markdown look shorter, but the other long lines are allowed to exceed the maximum line length because they are contain links (which don't count towards line length). Best way to see this is to add the markdownlint extension in VSCode - this will underline any markdown rule violations.

The other error indicates that you're referring to a localization string that doesn't appear in the localization file. Specifically: 
InvalidCurrentValuesError

This is caught by the new localization meta tests this repo opted into a couple of weeks back. Easy fix is to add the missing string to the localization file.

**Comment by raandree** [comment]
Thanks @PlagueHO, taking care of this right now.

**Comment by raandree** [comment]
I will start the migration to DSCResource.Template next week. Let me finish the Wins PR first and the one still open in xDnsServer.

**Pull request merged**
