### PR TITLE
Adding new WinsServerAddress resource

### LINKED ISSUE #199: WINS support
Looking for this to support both primary and secondary WINS server addresses.

### PR DESCRIPTION
**Pull request by raandree**
#### Pull Request (PR) description
The resource WinsServerAddress manages the WINS server for a given network adapter.

#### This Pull Request (PR) fixes the following issues
This fixes #199 

#### Task list
- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in README.md in resource folder.
- [x] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/networkingdsc/403)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Hi @raandree - looks like there is an extra parameter in your examples which is causing the tests to fail. I'll review once they're fixed.

**Comment by raandree** [comment]
Hi @PlagueHO. I have fixed my tests. The only test that is still failing is https://ci.appveyor.com/project/PowerShell/networkingdsc/builds/25093203#L5759. However, I have not touched the MSFT_NetAdapterState resource. When running the tests on my dev machine, all tests are running fine.

**Comment by PlagueHO** [comment]
Hi @raandree - that isn't actually failing - it shouldn't be happening, but that isn't the test failures. The test failures are here:
https://ci.appveyor.com/project/PowerShell/networkingdsc/builds/25093203?fullLog=true#L1654
https://ci.appveyor.com/project/PowerShell/networkingdsc/builds/25093203?fullLog=true#L1668
https://ci.appveyor.com/project/PowerShell/networkingdsc/builds/25093203?fullLog=true#L2444

They're just simple issues with your examples (you're including properties that don't exist in the MOF) and also a missing localization string.

I'm still a bit concerned about the other error you mentioned because it looks like a mock problem. But lets see if it still occurs after you've fixed the other issues. I can't see it occurring in the Dev branch. I wonder if it is something to do with a previous test putting the adapter in a bad state (which shouldn't matter for a unit test because of the Mocks).

**Comment by PlagueHO** [comment]
I can't find anyway that strange message you saw could appear. Everything is mocked correctly as far as I can tell. I couldn't see it occurring in other test runs. Maybe a one of glitch...?

**Comment by raandree** [comment]
Thanks for your help so far, @PlagueHO. There is some more work to do to get the tests fixed. I will continue on Monday with this.

**Comment by PlagueHO** [comment]
No worries @raandree - thank you for all your work!!!!! Love the contribution :grin:

**Comment by raandree** [comment]
@PlagueHO, finally all the tests are green...

**Comment by PlagueHO** [comment]
Sorry about the delay @raandree. I'll get onto this ASAP. Have limited time to do DSC till this weekend due to day job :cry:

**Pull request merged**
