### PR TITLE
Proposed fix for Issue #413

### LINKED ISSUE #413: NetBios: Does not support wildcards
The Netbios resource does not appear to support the use of wild cards as the help would suggest. Looking at the code this looks to be due to the static use of = in the WMI query and not replacing the * with %.

### PR DESCRIPTION
**Pull request by MKletz**
#### Pull Request (PR) description
Adjusted logic for NetBios resource WMI filter to correctly accept * as the help implies.

#### This Pull Request (PR) fixes the following issues
Fixes #413

#### Task list

- [ ] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md in resource folder.
- [ ] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/networkingdsc/414)

### CODE REVIEW

**Comment by MKletz** [comment]
Thank you for the feedback working on these now. Do you think the function should go in common for use by other resources? It's fairly generic.

**Comment by MKletz** [comment]
@PlagueHO I believe I have your comments addressed now. This is my first open source contribution so I apologize if I'm missing obvious things standards wise.

**Comment by PlagueHO** [comment]
Cool! Thanks @MKletz - I'll get onto the review tonight or tomorrow night! Thank you heaps for this!

**Comment by PlagueHO** [comment]
Hi @MKletz - let me know when you're good for me to review! Really keen to get this awesome addition into the kit.

**Comment by MKletz** [comment]
@PlagueHO sorry for the delay, missed the email for your last comment. I believe I've addressed your new comments

**Pull request merged**
