### PR TITLE
BREAKING CHANGE: Rename xNetworking to NetworkingDsc - Fixes #290

### LINKED ISSUE #290: Convert Module Name to NetworkingDsc
As per recent DSC Resource Naming guidelines changes:
https://github.com/PowerShell/DscResources/blob/master/Naming.md

### PR DESCRIPTION
**Pull request by PlagueHO**
**Pull Request (PR) description**
- BREAKING CHANGE:
  - Renamed xNetworking to NetworkingDsc - fixes [Issue #119](https://github.com/PowerShell/NetworkingDsc/issues/290).
  - Changed all MSFT\_xResourceName to MSFT\_ResourceName.
  - Updated DSCResources, Examples, Modules and Tests with new naming.
  - Updated Year to 2018 in License and Manifest.
  - Updated README.md from xNetworking to NetworkingDsc.

**This Pull Request (PR) fixes the following issues:**
- Fixes #290 

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [x] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [x] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

@tysonjhayes or @johlju - this is a bit of a mega one so there is no rush on it. But if either of you wouldn't mind reviewing that would be +++ awesome!

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xnetworking/330)

### CODE REVIEW

**Comment by johlju** [comment]
Reviewed 475 of 676 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[README.md, line 5 at r1](https://reviewable.io/reviews/powershell/xnetworking/330#-LBorcyd2ih_uDjcgvFy:-LBorcyd2ih_uDjcgvFz:b-4ln93y) ([raw file](https://github.com/powershell/xnetworking/blob/c3c05c0cdfcd6e939bbab795f6e4d8d196433797/README.md#L5)):*
> ```Markdown
> The **NetworkingDsc** module contains the following resources:
> 
> - **xDefaultGatewayAddress**: Sets a node's default gateway address.
> ```

These named should be updated.n

---

*[README.md, line 72 at r1](https://reviewable.io/reviews/powershell/xnetworking/330#-LBorRos8oVZ_aZw5JRt:-LBorRos8oVZ_aZw5JRu:b-qej0gc) ([raw file](https://github.com/powershell/xnetworking/blob/c3c05c0cdfcd6e939bbab795f6e4d8d196433797/README.md#L72)):*
> ```Markdown
> ## Known Issues
> 
> ### xFirewall Known Issues
> ```

This should be renamed? Thorughout this section.

---

*[Modules/NetworkingDsc/DSCResources/MSFT_DhcpClient/MSFT_DhcpClient.schema.mof, line 1 at r1](https://reviewable.io/reviews/powershell/xnetworking/330#-LBos7IA6BVdi8cWWFIM:-LBos7IA6BVdi8cWWFIN:b-djmo81) ([raw file](https://github.com/powershell/xnetworking/blob/c3c05c0cdfcd6e939bbab795f6e4d8d196433797/Modules/NetworkingDsc/DSCResources/MSFT_DhcpClient/MSFT_DhcpClient.schema.mof#L1)):*
> ```
> DHCPClient
> ```

Non-blocking: Should we rename this to "DhcpClient"? Lower letters 'hcp'?

---

*[Modules/NetworkingDsc/DSCResources/MSFT_DNSServerAddress/MSFT_DNSServerAddress.schema.mof, line 2 at r1](https://reviewable.io/reviews/powershell/xnetworking/330#-LBosjUu1bWPRr-D58X6:-LBosjUu1bWPRr-D58X7:b-v0tfvi) ([raw file](https://github.com/powershell/xnetworking/blob/c3c05c0cdfcd6e939bbab795f6e4d8d196433797/Modules/NetworkingDsc/DSCResources/MSFT_DNSServerAddress/MSFT_DNSServerAddress.schema.mof#L2)):*
> ```
> DNSServerAddress
> ```

Non-blocking: Maybe rename to 'DnsServerAddress'?

---

*[Modules/NetworkingDsc/DSCResources/MSFT_NetAdapterRDMA/MSFT_NetAdapterRDMA.schema.mof, line 1 at r1](https://reviewable.io/reviews/powershell/xnetworking/330#-LBouoN54tkqOE_-fSPM:-LBouoN54tkqOE_-fSPN:b9c7spw) ([raw file](https://github.com/powershell/xnetworking/blob/c3c05c0cdfcd6e939bbab795f6e4d8d196433797/Modules/NetworkingDsc/DSCResources/MSFT_NetAdapterRDMA/MSFT_NetAdapterRDMA.schema.mof#L1)):*
> ```
> [ClassVersion("1.0.0.0"), FriendlyName("NetAdapterRDMA")]
> ```

Non-blocking: Maybe rename to 'NetAdapterRdma'? 

---

*[Modules/NetworkingDsc/DSCResources/MSFT_NetBIOS/MSFT_NetBIOS.schema.mof, line 2 at r1](https://reviewable.io/reviews/powershell/xnetworking/330#-LBovHvYBo1wWl3e7rEh:-LBovHvYBo1wWl3e7rEi:bgaot9j) ([raw file](https://github.com/powershell/xnetworking/blob/c3c05c0cdfcd6e939bbab795f6e4d8d196433797/Modules/NetworkingDsc/DSCResources/MSFT_NetBIOS/MSFT_NetBIOS.schema.mof#L2)):*
> ```
> NetBIOS
> ```

Non-blocking: Maybe rename to 'NetBios'

---

*[Modules/NetworkingDsc/DSCResources/MSFT_WinsSetting/MSFT_WINSSetting.schema.mof, line 1 at r1](https://reviewable.io/reviews/powershell/xnetworking/330#-LBovw5M4bd7fgIM66xH:-LBovw5M4bd7fgIM66xI:b-84198i) ([raw file](https://github.com/powershell/xnetworking/blob/c3c05c0cdfcd6e939bbab795f6e4d8d196433797/Modules/NetworkingDsc/DSCResources/MSFT_WinsSetting/MSFT_WINSSetting.schema.mof#L1)):*
> ```
> WINSSetting
> ```

Non-blocking: Maybe rename this to 'WinsSetting'? 

---

*[Modules/NetworkingDsc/Examples/Resources/DhcpClient/1-xDHCPClient_EnableDHCP.ps1, line 1 at r1](https://reviewable.io/reviews/powershell/xnetworking/330#-LBowC6S5tQ2k46_ubCx:-LBowC6S5tQ2k46_ubCy:bv9jxp8) ([raw file](https://github.com/powershell/xnetworking/blob/c3c05c0cdfcd6e939bbab795f6e4d8d196433797/Modules/NetworkingDsc/Examples/Resources/DhcpClient/1-xDHCPClient_EnableDHCP.ps1#L1)):*
> ```PowerShell
> <#
> ```

Filename is wrong on this file.

---

*[Modules/xNetworking/Examples/Resources/xDnsServerAddress/1-xDnsServerAddress.ps1, line 1 at r1](https://reviewable.io/reviews/powershell/xnetworking/330#-LBowMCJDQoPku6eNG_0:-LBowMCJDQoPku6eNG_1:bngjizn) ([raw file](https://github.com/powershell/xnetworking/blob/6bf4d3e4833cdff4b5cad5cc745f021e97b7e10b/Modules/xNetworking/Examples/Resources/xDnsServerAddress/1-xDnsServerAddress.ps1#L1)):*
> ```PowerShell
> <#
> ```

Filename is wrong.

---

*[Modules/xNetworking/Examples/Resources/xDnsServerAddress/2-xDnsServerAddress_PrimaryAndSecondary.ps1, line 1 at r1](https://reviewable.io/reviews/powershell/xnetworking/330#-LBowULFEKK2T9T18LvC:-LBowULFEKK2T9T18LvD:bngjizn) ([raw file](https://github.com/powershell/xnetworking/blob/6bf4d3e4833cdff4b5cad5cc745f021e97b7e10b/Modules/xNetworking/Examples/Resources/xDnsServerAddress/2-xDnsServerAddress_PrimaryAndSecondary.ps1#L1)):*
> ```PowerShell
> <#
> ```

Filename is wrong.

---

*[Modules/xNetworking/Examples/Resources/xDnsServerAddress/3-xDnsServerAddress_EnableDHCP.ps1, line 1 at r1](https://reviewable.io/reviews/powershell/xnetworking/330#-LBowZjX7lcqA90rF7sI:-LBowZjX7lcqA90rF7sJ:bngjizn) ([raw file](https://github.com/powershell/xnetworking/blob/6bf4d3e4833cdff4b5cad5cc745f021e97b7e10b/Modules/xNetworking/Examples/Resources/xDnsServerAddress/3-xDnsServerAddress_EnableDHCP.ps1#L1)):*
> ```PowerShell
> <#
> ```

Filename is wrong.

---

*[Modules/xNetworking/Examples/Resources/xFirewall/1-xFirewall_AddFirewallRule.ps1, line 1 at r1](https://reviewable.io/reviews/powershell/xnetworking/330#-LBowb6v84oGQK6nfwxV:-LBowb6v84oGQK6nfwxW:bngjizn) ([raw file](https://github.com/powershell/xnetworking/blob/6bf4d3e4833cdff4b5cad5cc745f021e97b7e10b/Modules/xNetworking/Examples/Resources/xFirewall/1-xFirewall_AddFirewallRule.ps1#L1)):*
> ```PowerShell
> <#
> ```

Filename is wrong.

---

*[Modules/xNetworking/Examples/Resources/xFirewall/3-xFirewall_AddFirewallRuleToExistingGroup.ps1, line 1 at r1](https://reviewable.io/reviews/powershell/xnetworking/330#-LBowkcz5Tp34NK3dxb_:-LBowkcz5Tp34NK3dxba:bz25ki0) ([raw file](https://github.com/powershell/xnetworking/blob/6bf4d3e4833cdff4b5cad5cc745f021e97b7e10b/Modules/xNetworking/Examples/Resources/xFirewall/3-xFirewall_AddFirewallRuleToExistingGroup.ps1#L1)):*
> ```PowerShell
> <#
> ```

Filename is wrong. Throughout.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xnetworking/330)*

**Comment by PlagueHO** [comment]
Review status: 208 of 243 files reviewed at latest revision, 9 unresolved discussions.

---

*[README.md, line 5 at r1](https://reviewable.io/reviews/powershell/xnetworking/330#-LBorcyd2ih_uDjcgvFy:-LBtHLsC3W933WuDfv25:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/c3c05c0cdfcd6e939bbab795f6e4d8d196433797/README.md#L5)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

These named should be updated.n
</blockquote></details>

Done.

---

*[README.md, line 72 at r1](https://reviewable.io/reviews/powershell/xnetworking/330#-LBorRos8oVZ_aZw5JRt:-LBtHMVn0fm9kaA-rIRe:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/c3c05c0cdfcd6e939bbab795f6e4d8d196433797/README.md#L72)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

This should be renamed? Thorughout this section.
</blockquote></details>

Done.

---

*[Modules/NetworkingDsc/Examples/Resources/DhcpClient/1-xDHCPClient_EnableDHCP.ps1, line 1 at r1](https://reviewable.io/reviews/powershell/xnetworking/330#-LBowC6S5tQ2k46_ubCx:-LBtLOBG1FwpXAJsdl07:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/c3c05c0cdfcd6e939bbab795f6e4d8d196433797/Modules/NetworkingDsc/Examples/Resources/DhcpClient/1-xDHCPClient_EnableDHCP.ps1#L1)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Filename is wrong on this file.
</blockquote></details>

Done.

---

*[Modules/NetworkingDsc/DSCResources/MSFT_DhcpClient/MSFT_DhcpClient.schema.mof, line 1 at r1](https://reviewable.io/reviews/powershell/xnetworking/330#-LBos7IA6BVdi8cWWFIM:-LBtHval3Gc93I_aaNX2:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/c3c05c0cdfcd6e939bbab795f6e4d8d196433797/Modules/NetworkingDsc/DSCResources/MSFT_DhcpClient/MSFT_DhcpClient.schema.mof#L1)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> DHCPClient
> ```

Non-blocking: Should we rename this to "DhcpClient"? Lower letters 'hcp'?
</blockquote></details>

Done.

---

*[Modules/NetworkingDsc/DSCResources/MSFT_DNSServerAddress/MSFT_DNSServerAddress.schema.mof, line 2 at r1](https://reviewable.io/reviews/powershell/xnetworking/330#-LBosjUu1bWPRr-D58X6:-LBtHxE242e47DMGRcwx:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/c3c05c0cdfcd6e939bbab795f6e4d8d196433797/Modules/NetworkingDsc/DSCResources/MSFT_DNSServerAddress/MSFT_DNSServerAddress.schema.mof#L2)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> DNSServerAddress
> ```

Non-blocking: Maybe rename to 'DnsServerAddress'?
</blockquote></details>

Done.

---

*[Modules/NetworkingDsc/DSCResources/MSFT_NetAdapterRDMA/MSFT_NetAdapterRDMA.schema.mof, line 1 at r1](https://reviewable.io/reviews/powershell/xnetworking/330#-LBouoN54tkqOE_-fSPM:-LBtJ_rx7OJ056XPSbCH:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/c3c05c0cdfcd6e939bbab795f6e4d8d196433797/Modules/NetworkingDsc/DSCResources/MSFT_NetAdapterRDMA/MSFT_NetAdapterRDMA.schema.mof#L1)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Non-blocking: Maybe rename to 'NetAdapterRdma'? 
</blockquote></details>

Done.

---

*[Modules/NetworkingDsc/DSCResources/MSFT_NetBIOS/MSFT_NetBIOS.schema.mof, line 2 at r1](https://reviewable.io/reviews/powershell/xnetworking/330#-LBovHvYBo1wWl3e7rEh:-LBtKpES1Pt9RyiLb1Rj:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/c3c05c0cdfcd6e939bbab795f6e4d8d196433797/Modules/NetworkingDsc/DSCResources/MSFT_NetBIOS/MSFT_NetBIOS.schema.mof#L2)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> NetBIOS
> ```

Non-blocking: Maybe rename to 'NetBios'
</blockquote></details>

Done.

---

*[Modules/NetworkingDsc/DSCResources/MSFT_WinsSetting/MSFT_WINSSetting.schema.mof, line 1 at r1](https://reviewable.io/reviews/powershell/xnetworking/330#-LBovw5M4bd7fgIM66xH:-LBtKqI_9pPzrqnQNCUE:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/c3c05c0cdfcd6e939bbab795f6e4d8d196433797/Modules/NetworkingDsc/DSCResources/MSFT_WinsSetting/MSFT_WINSSetting.schema.mof#L1)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> WINSSetting
> ```

Non-blocking: Maybe rename this to 'WinsSetting'? 
</blockquote></details>

Done.

---

*[Modules/xNetworking/Examples/Resources/xDnsServerAddress/1-xDnsServerAddress.ps1, line 1 at r1](https://reviewable.io/reviews/powershell/xnetworking/330#-LBowMCJDQoPku6eNG_0:-LBtLOyh1_BzGqh6Swij:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/6bf4d3e4833cdff4b5cad5cc745f021e97b7e10b/Modules/xNetworking/Examples/Resources/xDnsServerAddress/1-xDnsServerAddress.ps1#L1)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Filename is wrong.
</blockquote></details>

Done.

---

*[Modules/xNetworking/Examples/Resources/xDnsServerAddress/2-xDnsServerAddress_PrimaryAndSecondary.ps1, line 1 at r1](https://reviewable.io/reviews/powershell/xnetworking/330#-LBowULFEKK2T9T18LvC:-LBtLQ-C3y8bw-iIv866:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/6bf4d3e4833cdff4b5cad5cc745f021e97b7e10b/Modules/xNetworking/Examples/Resources/xDnsServerAddress/2-xDnsServerAddress_PrimaryAndSecondary.ps1#L1)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Filename is wrong.
</blockquote></details>

Done.

---

*[Modules/xNetworking/Examples/Resources/xDnsServerAddress/3-xDnsServerAddress_EnableDHCP.ps1, line 1 at r1](https://reviewable.io/reviews/powershell/xnetworking/330#-LBowZjX7lcqA90rF7sI:-LBtLQep2hrqJQh8JjHC:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/6bf4d3e4833cdff4b5cad5cc745f021e97b7e10b/Modules/xNetworking/Examples/Resources/xDnsServerAddress/3-xDnsServerAddress_EnableDHCP.ps1#L1)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Filename is wrong.
</blockquote></details>

Done.

---

*[Modules/xNetworking/Examples/Resources/xFirewall/1-xFirewall_AddFirewallRule.ps1, line 1 at r1](https://reviewable.io/reviews/powershell/xnetworking/330#-LBowb6v84oGQK6nfwxV:-LBtLoI4AdywTi3cAjrZ:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/6bf4d3e4833cdff4b5cad5cc745f021e97b7e10b/Modules/xNetworking/Examples/Resources/xFirewall/1-xFirewall_AddFirewallRule.ps1#L1)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Filename is wrong.
</blockquote></details>

Done.

---

*[Modules/xNetworking/Examples/Resources/xFirewall/3-xFirewall_AddFirewallRuleToExistingGroup.ps1, line 1 at r1](https://reviewable.io/reviews/powershell/xnetworking/330#-LBowkcz5Tp34NK3dxb_:-LBtLpbr4v-ckU6-CbXz:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/6bf4d3e4833cdff4b5cad5cc745f021e97b7e10b/Modules/xNetworking/Examples/Resources/xFirewall/3-xFirewall_AddFirewallRuleToExistingGroup.ps1#L1)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Filename is wrong. Throughout.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xnetworking/330)*

**Comment by PlagueHO** [comment]
Hi @Johlju - I think this is all sorted now. I had to do a two pass rename process to change the case of some of the files.

---

Review status: 203 of 244 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xnetworking/330#-:-LBtVAJeAulqlAFAmjB0:b-42vgpt)*

**Comment by johlju** [comment]
Reviewed 37 of 676 files at r1, 41 of 102 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[README.md, line 74 at r2](https://reviewable.io/reviews/powershell/xnetworking/330#-LBtTxAKDXWlhkgOg-M0:-LBtTxAKDXWlhkgOg-M1:bg8ies2) ([raw file](https://github.com/powershell/xnetworking/blob/f38cf1757d042a2798a6387077d7e734ea0772a7/README.md#L74)):*
> ```
> when applying Firewall configuration
> ```

Maybe 'when using the resource Firewall in configurations' would read better? 

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xnetworking/330)*

**Comment by johlju** [comment]
@PlagueHO Just a tiny comment left. 🙂

**Comment by PlagueHO** [comment]
All done! Thanks again @Johlju

---

Review status: 242 of 243 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 74 at r2](https://reviewable.io/reviews/powershell/xnetworking/330#-LBtTxAKDXWlhkgOg-M0:-LBt_Oym5laNU6VMqron:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/f38cf1757d042a2798a6387077d7e734ea0772a7/README.md#L74)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> when applying Firewall configuration
> ```

Maybe 'when using the resource Firewall in configurations' would read better? 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xnetworking/330#-:-LBt_PzX5t0pWXFenzkT:bx7mlya)*

**Comment by johlju** [comment]
:lgtm:

@kwirkykat can you rename this repo?

@plagueho Awesome work! I could rename the repo, but I don't know if @kwirkykat does anything more that I haven't permission to (like AppVeyor).  

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xnetworking/330#-:-LBtaN8X8H8O-6JqUiM1:b-x68vet)*

**Comment by kwirkykat** [comment]
@PlagueHO @johlju Done

**Comment by tysonjhayes** [comment]
Good job @PlagueHO - look forward to updating my resources to point to the new naming. 😁

**Comment by PlagueHO** [comment]
Awesome! Thanks @johlju , @kwirkykat  and @tysonjhayes ! I'm looking forward to updating all our configs as well!

**Pull request merged**
