### PR TITLE
NetAdapterState: New resource to enable or disable a network adapter

### LINKED ISSUE #365: Possibility to enable a Network Adapter
I searched through the resources and ended up writing a small script resource to ensure, because I didn't find what I was looking for.
I'd like to ensure, that a network adapter is enabled, but it seems, that there's no fitting resource?

### PR DESCRIPTION
**Pull request by danielboth**
#### Pull Request (PR) description
NetAdapterState is a new resource which controls the state of a network adapter. It allows for enabling or disabling of a network adapter based on the name of the network adapter.

#### This Pull Request (PR) fixes the following issues

- Fixes #365 

#### Task list

- [X] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [X] Resource documentation added/updated in README.md in resource folder.
- [X] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [X] Comment-based help added/updated.
- [X] Localization strings added/updated in all localization files as appropriate.
- [X] Examples appropriately added/updated.
- [X] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [X] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [X] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/networkingdsc/379)

### CODE REVIEW

**Comment by danielboth** [comment]
Hi @PlagueHO, thanks for the detailed review!

On the topic of integration tests, I did not create any because I did not want to enable / disable any random adapter on the system of a user. Adding a loopback adapter could be a fix, but would that not add too many external dependencies in the build? Eg, we then need devcon.exe + add the loopback adapter in the build, which all has to come from some location on the internet, which could also fail. I would prefer to keep the tests as atomic as possible, but I don't think that adding these binaries (devcon.exe) to this repository is the way to go?

Let me know what you think.

**Comment by PlagueHO** [comment]
Hi @danielboth - sorry I haven't completed this one yet. I see you made all the changes. Can you resolve the conflicts and I'll try and complete the review for you ASAP?

**Comment by PlagueHO** [comment]
@danielboth - regarding the integration tests, we've already addressed the Loopback/DevCon issue and have a solution. See:
https://github.com/PowerShell/NetworkingDsc/blob/dev/Tests/Integration/MSFT_FirewallProfile.Integration.Tests.ps1#L22
https://github.com/PowerShell/NetworkingDsc/blob/dev/Tests/Integration/MSFT_FirewallProfile.Integration.Tests.ps1#L44
https://github.com/PowerShell/NetworkingDsc/blob/dev/Tests/Integration/MSFT_FirewallProfile.Integration.Tests.ps1#L158

It is reasonably easy to implement I think.

**Comment by danielboth** [comment]
Hi @PlagueHO, ok indeed, that way I can easily add the integration test. I added an integration test and resolved the merge conflict.

**Comment by PlagueHO** [comment]
@danielboth - this is looking good - thank you for all your work and your patience! :grin: Can you rebase and I'll merge?

**Pull request merged**
