### PR TITLE
Added WaitForNetworkTeam resource - Fixes #319

### LINKED ISSUE #319: xNetworkTeam: LACP handshake delay ignored?
I'm using xNetworking 5.5.0.0 to build a NIC team on a Win2016 server:

ConfigurationMode              : ApplyAndAutoCorrect
ConfigurationModeFrequencyMins : 30

`
<snip>
  		xNetworkTeam NICTeam {
			Name                   = 'TEAM01'
			TeamingMode            = 'LACP'
			LoadBalancingAlgorithm = 'Dynamic'
			TeamMembers            = 'NIC-1', 'NIC-2'
			Ensure                 = 'Present'
		}
		xDhcpClient DisableDhcpClient {
			State          = 'Disabled'
			InterfaceAlias = 'TEAM01'
			AddressFamily  = 'IPv4'
			DependsOn      = '[xNetworkTeam]NICTeam'
		}
		xIPAddress IPv4Address {
			IPAddress      = "$IPaddress/24"
			InterfaceAlias = 'TEAM01'
			AddressFamily  = 'IPv4'
			DependsOn      = '[xDhcpClient]DisableDhcpClient'
		}
		xDefaultGatewayAddress SetDefaultGateway {
			Address        = "$($GWaddress)"
			InterfaceAlias = 'TEAM01'
			AddressFamily  = 'IPv4'
			DependsOn      = '[xIPAddress]IPv4Address'
		}
<snap>
`

the initial run of Start-DSCConfiguration fails to configure the IP address and/or the default gateway. But when I walk away and check again next morning, all my resources report "InDesiredState"

BUT: when I watch the verbose output of Start-DSCConfiguration, the above steps complete within seconds. When I configure this manually, my LACP team needs 1-2 minutes to complete the LACP handshake and to come online.

I have not found a "DSC delay" resource yet or I would insert that between NICTeam" and "DisableDhcpClient" to verify my guesstimated timing problem here. running Start-DSCConfiguration twice does not help. running Start-DSCConfiguration again 10 minutes later seems to work.

any chance that this is a bug ignoring the team status and continuing too fast? or just a noob error with the configuration above??

other ideas and/or suggestions ?

thanks in advance

### PR DESCRIPTION
**Pull request by PlagueHO**
**Pull Request (PR) description**
This PR adds the WaitForNetworkTeam resource that will wait for a network team to come 'up' before proceeding.

**This Pull Request (PR) fixes the following issues:**
- Fixes #319

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [x] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [x] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

@johlju or @tysonjhayes - would either of you mind reviewing if you have time?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/networkingdsc/335)

### CODE REVIEW

**Comment by johlju** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[Tests/Integration/MSFT_WaitForNetworkTeam.Integration.Tests.ps1, line 12 at r1](https://reviewable.io/reviews/powershell/networkingdsc/335#-LE97ZHj4z9d73Kbr9vx:-LE97ZHj4z9d73Kbr9vy:b-41acdt) ([raw file](https://github.com/powershell/networkingdsc/blob/84578f5b4caa9bd399c7502e816646ca5fdee77c/Tests/Integration/MSFT_WaitForNetworkTeam.Integration.Tests.ps1#L12)):*
> ```PowerShell
>     SKU machines will support it.
> #>
> return
> ```

Should we write out a warning that it cannot run in AppVeyor when `$env_APPVEYOR -eq $true` and return? Would be cleaner if the integration test could run when manually started in a lab without needing to change the test code?

---

*[Tests/Unit/MSFT_WaitForNetworkTeam.Tests.ps1, line 106 at r1](https://reviewable.io/reviews/powershell/networkingdsc/335#-LE98NKvCTEfgzoEO-3o:-LE98NKvCTEfgzoEO-3p:b-4or0xp) ([raw file](https://github.com/powershell/networkingdsc/blob/84578f5b4caa9bd399c7502e816646ca5fdee77c/Tests/Unit/MSFT_WaitForNetworkTeam.Tests.ps1#L106)):*
> ```
> Set-targetResource
> ```

Set-TargetResource (upper 'T'). Throughout.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/networkingdsc/335)*

**Comment by PlagueHO** [comment]
Review status: 7 of 13 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[Tests/Integration/MSFT_WaitForNetworkTeam.Integration.Tests.ps1, line 12 at r1](https://reviewable.io/reviews/powershell/networkingdsc/335#-LE97ZHj4z9d73Kbr9vx:-LEEIiqg6LRkoH59Ouj-:b-urgs11) ([raw file](https://github.com/powershell/networkingdsc/blob/84578f5b4caa9bd399c7502e816646ca5fdee77c/Tests/Integration/MSFT_WaitForNetworkTeam.Integration.Tests.ps1#L12)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Should we write out a warning that it cannot run in AppVeyor when `$env_APPVEYOR -eq $true` and return? Would be cleaner if the integration test could run when manually started in a lab without needing to change the test code?
</blockquote></details>

I've done this and also in the other Network Team integration tests. I added a new Common Test Helper function to reduce code duplication for these.

---

*[Tests/Unit/MSFT_WaitForNetworkTeam.Tests.ps1, line 106 at r1](https://reviewable.io/reviews/powershell/networkingdsc/335#-LE98NKvCTEfgzoEO-3o:-LEEIrz90iOg5SZLPj57:b-896fix) ([raw file](https://github.com/powershell/networkingdsc/blob/84578f5b4caa9bd399c7502e816646ca5fdee77c/Tests/Unit/MSFT_WaitForNetworkTeam.Tests.ps1#L106)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> Set-targetResource
> ```

Set-TargetResource (upper 'T'). Throughout.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/networkingdsc/335)*

**Comment by PlagueHO** [comment]
All done now! Thanks @johlju

---

Review status: 7 of 13 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/powershell/networkingdsc/335#-:-LEEJ-b6-op56L60tIh9:bk9cqk8)*

**Comment by johlju** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[a discussion](https://reviewable.io/reviews/powershell/networkingdsc/335#-LEESZRxBqO-oTQjh6q3:-LE98o-S2bE5r13poYpZ:b-6of7bb) (no related file):*
There are merge conflicts that need to be resolved.

---

*[Tests/TestHelpers/CommonTestHelper.psm1, line 112 at r2](https://reviewable.io/reviews/powershell/networkingdsc/335#-LEESKbr41xWDZnGyoHm:-LEESKbr41xWDZnGyoHn:b-1lqn6k) ([raw file](https://github.com/powershell/networkingdsc/blob/085a3ebd30b84c52828cbe49612522e7e3240f68/Tests/TestHelpers/CommonTestHelper.psm1#L112)):*
> ```PowerShell
>     if ($NetworkAdapters.Count -lt 2)
>     {
>         Write-Warning -Message 'Performing Network Teaming integration tests requires at least two compatible network adapters to be specified.'
> ```

Maybe add to the message how they add those adapters? Point them to the comment-based help in each test maybe? :)

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/networkingdsc/335)*

**Comment by PlagueHO** [comment]
Review status: 11 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/powershell/networkingdsc/335#-LEESZRxBqO-oTQjh6q3:-LEIpfNZ3TujG55PdgGN:b-hsjn9w) (no related file):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

There are merge conflicts that need to be resolved.
</blockquote></details>

Fixed merge conflict and also added line missing from README.MD

---

*[Tests/TestHelpers/CommonTestHelper.psm1, line 112 at r2](https://reviewable.io/reviews/powershell/networkingdsc/335#-LEESKbr41xWDZnGyoHm:-LEIpBsk0q-vTBzq67PI:b-896fix) ([raw file](https://github.com/powershell/networkingdsc/blob/085a3ebd30b84c52828cbe49612522e7e3240f68/Tests/TestHelpers/CommonTestHelper.psm1#L112)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Maybe add to the message how they add those adapters? Point them to the comment-based help in each test maybe? :)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/networkingdsc/335)*

**Comment by PlagueHO** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[a discussion](https://reviewable.io/reviews/powershell/networkingdsc/335#-LEESZRxBqO-oTQjh6q3:-LELNz9f39IkX9cXQBci:bscnimz) (no related file):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Good catch! There a quite a lot of places to change when adding a new resource. :/ Maybe we should try to get more into the auto-documentation (when we have time). :slightly_smiling_face: 
</blockquote></details>

Definitely! This should be able to be done as well I think!

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/networkingdsc/335)*

**Pull request merged**
